parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'

ignorePatterns:
  - 'build'

plugins:
  - '@typescript-eslint'

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:prettier/recommended'

rules:
  '@typescript-eslint/consistent-type-definitions': ['error', 'type']
  '@typescript-eslint/promise-function-async': 'off'
